<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>QAnimator.Encoder</RootNamespace>
    <AssemblyName>QAnimatorEncoder</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Unity/Runtime/QAnimatorDecoder.cs" Link="Preview/QAnimatorDecoder.cs" />
    <Compile Include="../Unity/Runtime/QAnimatorFormat.cs" Link="Preview/QAnimatorFormat.cs" />
  </ItemGroup>
</Project>
