<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Encoder/Encoding/VideoConversion.cs" Link="Encoder/VideoConversion.cs" />
    <Compile Include="../../Encoder/Ffmpeg/FfmpegTools.cs" Link="Encoder/FfmpegTools.cs" />
    <Compile Include="../../Encoder/Format/QAnimatorFormat.cs" Link="Encoder/QAnimatorFormat.cs" />
    <Compile Include="../../Encoder/Encoding/QAnimatorEncoder.cs" Link="Encoder/QAnimatorEncoder.cs" />
    <Compile Include="../../Unity/Runtime/QAnimatorFormat.cs" Link="Unity/QAnimatorFormat.cs" />
    <Compile Include="../../Unity/Runtime/QAnimatorDecoder.cs" Link="Unity/QAnimatorDecoder.cs" />
  </ItemGroup>
</Project>
